# Generated by Django 2.2.8 on 2020-06-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='date_posted',
        ),
    ]
