# Generated by Django 2.2.8 on 2020-06-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0002_auto_20200606_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='overall_score',
            new_name='content_average',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='creativity',
        ),
        migrations.AddField(
            model_name='rating',
            name='design_average',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='usability_average',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awward.Post'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
