# Generated by Django 2.2.8 on 2020-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0003_auto_20200606_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content_average',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design_average',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability_average',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
