# Generated by Django 2.2.8 on 2020-06-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('awward', '0005_auto_20200606_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='project',
        ),
        migrations.AddField(
            model_name='rating',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
