# Generated by Django 2.2.8 on 2020-06-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0006_auto_20200606_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='author',
        ),
        migrations.AddField(
            model_name='rating',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rater', to='awward.Post'),
        ),
    ]
